#  Dockerfile for Node Express Backend

FROM node:14.1-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./

RUN cd server && npm install --silent
RUN cd client && npm install --silent && npm run build

# Copy app source code
COPY . .

# Exports
EXPOSE 5000

CMD ["npm","start"]