export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESSFUL = "FETCH_EMPLOYEES_SUCCESSFUL";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESSFUL = "ADD_EMPLOYEE_SUCCESSFUL";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_REQUEST = "EDIT_EMPLOYEE_REQUEST";
export const EDIT_EMPLOYEE_SUCCESSFUL = "EDIT_EMPLOYEE_SUCCESSFUL";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESSFUL = "DELETE_EMPLOYEE_SUCCESSFUL";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";

export const SEARCH_EMPLOYEE_REQUEST = "SEARCH_EMPLOYEE_REQUEST";
export const SEARCH_EMPLOYEE_SUCCESSFUL = "SEARCH_EMPLOYEE_SUCCESSFUL";
export const SEARCH_EMPLOYEE_FAILED = "SEARCH_EMPLOYEE_FAILED";